#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := putt-pilot

# Instead of using default "main" directory, I just want to call it "src", so compile that too
EXTRA_COMPONENT_DIRS = $(PROJECT_PATH)/app/src $(PROJECT_PATH)/helpers/helpers_src

include $(IDF_PATH)/make/project.mk

